<?xml version="1.0"?>
<robot name="kaqi_hardware" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find kaqi_description)/urdf/calibrate.xacro" />

  <!-- len: cm -->
  <xacro:macro name="kaqi_standoff_xx" params="parent number x_loc y_loc z_loc len">
    <joint name="standoff_${len}_${number}_joint" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="standoff_${len}_${number}_link" />
    </joint>

    <link name="standoff_${len}_${number}_link">
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>
      <visual>
        <origin xyz="0 0 ${len/200.0}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${len/100.0}" radius="0.005"/>
        </geometry>

        <material name="">
          <color rgba="1 1 1 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${len/200.0}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${len/100.0}" radius="0.005"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="kaqi_standoff_kinect" params="parent number x_loc y_loc z_loc len">
    <joint name="standoff_kinect_${number}_joint" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="standoff_kinect_${number}_link" />
    </joint>

    <link name="standoff_kinect_${number}_link">
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001" />
      </inertial>
      <visual>
        <origin xyz="0 0 ${len/2.0}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${len}" radius="0.005"/>
        </geometry>
	<material name="">
          <color rgba="1 1 1 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${len/2.0}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${len}" radius="0.005"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="kaqi_plate1" params="parent number x_loc y_loc z_loc">
    <joint name="plate1_${number}_joint" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="plate1_${number}_link" />
    </joint>

    <link name="plate1_${number}_link">
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>
      <visual>
        <origin xyz="0 0 0.0" rpy="${M_PI/2.0} 0 ${-M_PI/2.0}" />
        <geometry>
          <mesh filename="package://kaqi_description/meshes/plate1.stl"/>
        </geometry>
        <material name="">
          <color rgba="1 1 1 0.5" />
          <ambient>1 1 1 0.5</ambient>
          <diffuse>1 1 1 0.5</diffuse>
          <specular>0.1 0.1 0.1 128</specular>
          <emissive>0 0 0 0</emissive>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0.0025" rpy="0 0 0" />
        <geometry>
          <box size=".36 .36 .005"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

</robot>
